apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: multiapp-vms
spec:
  scaleTargetRef:
    kind: VirtualMachinePool
    name: multiapp-vms
    apiVersion: pool.kubevirt.io/v1alpha1
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 15
      policies:
      - type: Pods
        periodSeconds: 15
        value: 5
    scaleDown:
      stabilizationWindowSeconds: 15
      policies:
      - type: Pods
        periodSeconds: 15
        value: 5

