apiVersion: pool.kubevirt.io/v1alpha1
kind: VirtualMachinePool
metadata:
  labels:
    app: multiapp
  name: multiapp-vms
spec:
  replicas: 2
  selector:
    matchLabels:
      kubevirt.io/vmpool: multiapp
  virtualMachineTemplate:
    metadata:
      labels:
        kubevirt.io/vmpool: multiapp
    spec:
      running: true
      template:
        metadata:
          name: multiapp
          labels:
            kubevirt.io/vmpool: multiapp
            app: multiapp
        spec:
          domain:
            devices:
              disks:
              - disk:
                  bus: virtio
                name: containerdisk
            resources:
              requests:
                memory: 256Mi
                cpu: 500m
          terminationGracePeriodSeconds: 0
          volumes:
          - containerDisk:
              image: quay.io/apoczeka/vm:latest
            name: containerdisk 
